### ISSUE TITLE
RuntimeError: view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by VicenteAlex** [Intelligent-Computing-Lab-Yale/BNTT-Batch-Normalization-Through-Time#1]
Hello, thank you for uploading your work.

I have executed the code without changes with the following 2 configurations:

Python 3.6.9 + PyTorch 1.7.0+cu101
Python 3.8.7 + PyTorch 1.7.1+cpu

In both cases I run into the following error:

File "...\BNTT-Batch-Normalization-Through-Time\utills.py", line 22, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

Changing the line to any of the following solves the problem for me:

correct_k = correct[:k].reshape(-1).float().sum(0, keepdim=True)
correct_k = correct[:k].contiguous().view(-1).float().sum(0, keepdim=True)

Does it run without this change for you? Or should it be changed?

Best regards

**Comment by lotusroot-kim** [comment]
Hello, thank you for the suggestion.

In our configuration, the code works without changing the line.

If there are more future issues related to this line, we will update that line.

Thanks

**Comment by baimuchu** [comment]
actually, we also find this issue when we change the batchsize. So I think you can adapt the suggestion.
