### ISSUE TITLE
How to get the parameters of threshold?

### ISSUE THREAD

**Issue by manwu1994** [Intelligent-Computing-Lab-Yale/BNTT-Batch-Normalization-Through-Time#2]
Hi, when I try to print the parameters of your model, I can't get the dynamic threshold. Could you give me any advice about how to get the threshold parameters? Thank you so much for this great work and for your answer.

**Comment by lotusroot-kim** [comment]
Hi,

In our algorithm, we set all thresholds as 1. There is no "real" dynamic threshold.

We just show that learnable parameters in BNTT have the same effect as learnable parameters.

Thanks

**Comment by manwu1994** [comment]
Thank you for your reply.
