### ISSUE TITLE
Input spike not (0, 1) 

### ISSUE THREAD

**Issue by ngocqn** [Intelligent-Computing-Lab-Yale/BNTT-Batch-Normalization-Through-Time#3]
I found in your source code file model.py
def PoissonGen(inp, rescale_fac=2.0):
    rand_inp = torch.rand_like(inp).cuda()
    return torch.mul(torch.le(rand_inp * rescale_fac, torch.abs(inp)).float(), torch.sign(inp))

Inp is CIFAR-10, and CIFAR-100 images with transforms -> return will (-1, 0, +1) -> input spikes are three states.
While the input other layers are (0, 1).

**Comment by lotusroot-kim** [comment]
Hi,

We follow the previous work (https://github.com/nitin-rathi/hybrid-snn-conversion) where they empirically found that using three states input brings better performance.

This might not bring huge hardware overhead for SNNs.

Thanks
